In [2]:
import numpy as np

Matrix

In [3]:
np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12')

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [18]:
A = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Vectors

In [19]:
v=np.matrix('1;2;3')
v

matrix([[1],
        [2],
        [3]])

Dimensions

In [16]:
(m,n) = A.shape

(m,n)

(4, 3)

In [21]:
dim_v = v.shape

dim_v

(3, 1)

Matrix Indexing

In [23]:
A_23 = A[1,2]

A_23

6

Matrix Addition & Matrix-Scalar Multiplication

In [24]:
A = np.matrix('1, 2, 4; 5, 3, 2')
B = np.matrix('1, 3, 4; 1, 1, 1')

s=2

add_AB = A + B
add_AB

matrix([[2, 5, 8],
        [6, 4, 3]])

In [25]:
sub_AB = A-B
sub_AB 

matrix([[ 0, -1,  0],
        [ 4,  2,  1]])

In [26]:
mult_As=A*s
mult_As

matrix([[ 2,  4,  8],
        [10,  6,  4]])

In [28]:
div_As = A/s
div_As

matrix([[0.5, 1. , 2. ],
        [2.5, 1.5, 1. ]])

In [29]:
add_As = A+s
add_As

matrix([[3, 4, 6],
        [7, 5, 4]])

Matrix-Vector Multiplication

In [4]:
# Initialize matrix A 
A = np.matrix('1, 2, 3; 4, 5, 6;7, 8, 9')

# Initialize vector v 
v = np.matrix('1; 1; 1')

# Multiply A * v
Av = A * v

Av

matrix([[ 6],
        [15],
        [24]])

Matrix-Matrix Multiplication

In [5]:
# Initialize a 3 by 2 matrix 
A = np.matrix('1, 2; 3, 4;5, 6')

# Initialize a 2 by 1 matrix 
B = np.matrix('1; 2')

# We expect a resulting matrix of (3 by 2)*(2 by 1) = (3 by 1) 
mult_AB = A*B

mult_AB

matrix([[ 5],
        [11],
        [17]])

Identity Matrix 

In [6]:
# Initialize random matrices A and B 
A = np.matrix('1,2;4,5')
B = np.matrix('1,1;0,2')

# Initialize a 2 by 2 identity matrix
I = np.identity(2)

# The above notation is the same as I = [1,0;0,1]

# What happens when we multiply I*A ? 
IA = I*A 

IA

matrix([[1., 2.],
        [4., 5.]])

In [7]:
# How about A*I ? 
AI = A*I 
AI

matrix([[1., 2.],
        [4., 5.]])

In [8]:
# Compute A*B 
AB = A*B 
AB

matrix([[ 1,  5],
        [ 4, 14]])

In [9]:
# Is it equal to B*A? 
BA = B*A 
BA
# Note that IA = AI but AB != BA

matrix([[ 5,  7],
        [ 8, 10]])

In [10]:
# Initialize matrix A 
A = np.matrix('1,2,0;0,5,6;7,0,9')

# Transpose A 
np.transpose(A)

matrix([[1, 0, 7],
        [2, 5, 0],
        [0, 6, 9]])

In [12]:
# Take the inverse of A 
np.linalg.inv(A)

matrix([[ 0.34883721, -0.13953488,  0.09302326],
        [ 0.3255814 ,  0.06976744, -0.04651163],
        [-0.27131783,  0.10852713,  0.03875969]])

In [14]:
# What is A^(-1)*A? 
A_invA = np.linalg.inv(A)*A
A_invA.round()

matrix([[ 1., -0.,  0.],
        [-0.,  1., -0.],
        [-0.,  0.,  1.]])