In [3]:
import numpy as np

Matrix

In [4]:
np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12')

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [18]:
A = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Vectors

In [19]:
v=np.matrix('1;2;3')
v

matrix([[1],
        [2],
        [3]])

Dimensions

In [16]:
(m,n) = A.shape

(m,n)

(4, 3)

In [21]:
dim_v = v.shape

dim_v

(3, 1)

Matrix Indexing

In [23]:
A_23 = A[1,2]

A_23

6

Matrix Addition & Matrix-Scalar Multiplication

In [24]:
A = np.matrix('1, 2, 4; 5, 3, 2')
B = np.matrix('1, 3, 4; 1, 1, 1')

s=2

add_AB = A + B
add_AB

matrix([[2, 5, 8],
        [6, 4, 3]])

In [25]:
sub_AB = A-B
sub_AB 

matrix([[ 0, -1,  0],
        [ 4,  2,  1]])

In [26]:
mult_As=A*s
mult_As

matrix([[ 2,  4,  8],
        [10,  6,  4]])

In [28]:
div_As = A/s
div_As

matrix([[0.5, 1. , 2. ],
        [2.5, 1.5, 1. ]])

In [29]:
add_As = A+s
add_As

matrix([[3, 4, 6],
        [7, 5, 4]])